insert into trips (dep_port, arr_port) values ('Port of Singapore, Singapore', 'Port of Piraeus, Greece');
insert into trips (dep_port, arr_port) values ('Port of Yokohama, Japan', 'Port of Djibouti, Djibouti');
insert into trips (dep_port, arr_port) values ('Port of Suez, Egypt', 'Port of Reykjavik, Iceland');
insert into trips (dep_port, arr_port) values ('Port of Jakarta, Indonesia', 'Port of Callao, Peru');
insert into trips (dep_port, arr_port) values ('Port of Bangkok, Thailand', 'Port of Algiers, Algeria');
insert into trips (dep_port, arr_port) values ('Port of Hai Phong, Vietnam', 'Port of Thessaloniki, Greece');
insert into trips (dep_port, arr_port) values ('Port of Alexandria, Egypt', 'Port of Dublin, Ireland');
insert into trips (dep_port, arr_port) values ('Port of Yangon, Myanmar', 'Port of Constanta, Romania');
insert into trips (dep_port, arr_port) values ('Port of Melbourne, Australia', 'Port of Dakar, Senegal');
insert into trips (dep_port, arr_port) values ('Port of Santos, Brazil', 'Port of Luanda, Angola');
insert into trips (dep_port, arr_port) values ('Port of Noumea, New Caledonia', 'Port of Nouakchott, Mauritania');
insert into trips (dep_port, arr_port) values ('Port of Yangon, Myanmar', 'Port of Constanta, Romania');
insert into trips (dep_port, arr_port) values ('Port of Tanjung Pelepas, Malaysia', 'Port of Haifa, Israel');
insert into trips (dep_port, arr_port) values ('Port of Chittagong, Bangladesh', 'Port of Varna, Bulgaria');
insert into trips (dep_port, arr_port) values ('Port of Chittagong, Bangladesh', 'Port of Varna, Bulgaria');
insert into trips (dep_port, arr_port) values ('Port of Casablanca, Morocco', 'Port of Nuuk, Greenland');
insert into trips (dep_port, arr_port) values ('Port of Nuku''alofa, Tonga', 'Port of Monrovia, Liberia');
insert into trips (dep_port, arr_port) values ('Port of Antwerp, Belgium', 'Port of Felixstowe, UK');
insert into trips (dep_port, arr_port) values ('Port of Yokohama, Japan', 'Port of Djibouti, Djibouti');
insert into trips (dep_port, arr_port) values ('Port of Ningbo-Zhoushan, China', 'Port of Oslo, Norway');
insert into trips (dep_port, arr_port) values ('Port of Bangkok, Thailand', 'Port of Algiers, Algeria');
insert into trips (dep_port, arr_port) values ('Port of Jebel Ali, UAE', 'Port of St. Petersburg, Russia');
insert into trips (dep_port, arr_port) values ('Port of Hai Phong, Vietnam', 'Port of Thessaloniki, Greece');
insert into trips (dep_port, arr_port) values ('Port of Hai Phong, Vietnam', 'Port of Thessaloniki, Greece');
insert into trips (dep_port, arr_port) values ('Port of Suez, Egypt', 'Port of Reykjavik, Iceland');
insert into trips (dep_port, arr_port) values ('Port of Colombo, Sri Lanka', 'Port of Jeddah, Saudi Arabia');
insert into trips (dep_port, arr_port) values ('Port of Singapore, Singapore', 'Port of Piraeus, Greece');
insert into trips (dep_port, arr_port) values ('Port of Jebel Ali, UAE', 'Port of St. Petersburg, Russia');
insert into trips (dep_port, arr_port) values ('Port of Shanghai, China', 'Port of Valencia, Spain');
insert into trips (dep_port, arr_port) values ('Port of Ningbo-Zhoushan, China', 'Port of Oslo, Norway');
insert into trips (dep_port, arr_port) values ('Port of Mumbai, India', 'Port of Buenos Aires, Argentina');
insert into trips (dep_port, arr_port) values ('Port of Casablanca, Morocco', 'Port of Nuuk, Greenland');
insert into trips (dep_port, arr_port) values ('Port of Genoa, Italy', 'Port of Auckland, New Zealand');
insert into trips (dep_port, arr_port) values ('Port of Yokohama, Japan', 'Port of Djibouti, Djibouti');
insert into trips (dep_port, arr_port) values ('Port of Genoa, Italy', 'Port of Auckland, New Zealand');
insert into trips (dep_port, arr_port) values ('Port of Apia, Samoa', 'Port of Tema, Ghana');
insert into trips (dep_port, arr_port) values ('Port of Antwerp, Belgium', 'Port of Felixstowe, UK');
insert into trips (dep_port, arr_port) values ('Port of Jebel Ali, UAE', 'Port of St. Petersburg, Russia');
insert into trips (dep_port, arr_port) values ('Port of Yokohama, Japan', 'Port of Djibouti, Djibouti');
insert into trips (dep_port, arr_port) values ('Port of Mumbai, India', 'Port of Buenos Aires, Argentina');
insert into trips (dep_port, arr_port) values ('Port of Los Angeles, USA', 'Port of Vancouver, Canada');
insert into trips (dep_port, arr_port) values ('Port of Kaohsiung, Taiwan', 'Port of Istanbul, Turkey');
insert into trips (dep_port, arr_port) values ('Port of Tauranga, New Zealand', 'Port of Libreville, Gabon');
insert into trips (dep_port, arr_port) values ('Port of Guangzhou, China', 'Port of Helsinki, Finland');
insert into trips (dep_port, arr_port) values ('Port of Tauranga, New Zealand', 'Port of Libreville, Gabon');
insert into trips (dep_port, arr_port) values ('Port of Brisbane, Australia', 'Port of Abidjan, Ivory Coast');
insert into trips (dep_port, arr_port) values ('Port of Nuku''alofa, Tonga', 'Port of Monrovia, Liberia');
insert into trips (dep_port, arr_port) values ('Port of Jebel Ali, UAE', 'Port of St. Petersburg, Russia');
insert into trips (dep_port, arr_port) values ('Port of Le Havre, France', 'Port of San Antonio, Chile');
insert into trips (dep_port, arr_port) values ('Port of Chittagong, Bangladesh', 'Port of Varna, Bulgaria');
insert into trips (dep_port, arr_port) values ('Port of Papeete, French Polynesia', 'Port of Banjul, Gambia');
insert into trips (dep_port, arr_port) values ('Port of Genoa, Italy', 'Port of Auckland, New Zealand');
insert into trips (dep_port, arr_port) values ('Port of Fremantle, Australia', 'Port of Cotonou, Benin');
insert into trips (dep_port, arr_port) values ('Port of Colombo, Sri Lanka', 'Port of Jeddah, Saudi Arabia');
insert into trips (dep_port, arr_port) values ('Port of Rotterdam, Netherlands', 'Port of Marseille, France');
insert into trips (dep_port, arr_port) values ('Port of Sydney, Australia', 'Port of Dar es Salaam, Tanzania');
insert into trips (dep_port, arr_port) values ('Port of Papeete, French Polynesia', 'Port of Banjul, Gambia');
insert into trips (dep_port, arr_port) values ('Port of Tanjung Pelepas, Malaysia', 'Port of Haifa, Israel');
insert into trips (dep_port, arr_port) values ('Port of Honiara, Solomon Islands', 'Port of Conakry, Guinea');
insert into trips (dep_port, arr_port) values ('Port of Guangzhou, China', 'Port of Helsinki, Finland');
insert into trips (dep_port, arr_port) values ('Port of Long Beach, USA', 'Port of Montreal, Canada');
insert into trips (dep_port, arr_port) values ('Port of Auckland, New Zealand', 'Port of Douala, Cameroon');
insert into trips (dep_port, arr_port) values ('Port of Los Angeles, USA', 'Port of Vancouver, Canada');
insert into trips (dep_port, arr_port) values ('Port of Fremantle, Australia', 'Port of Cotonou, Benin');
insert into trips (dep_port, arr_port) values ('Port of Apia, Samoa', 'Port of Tema, Ghana');
insert into trips (dep_port, arr_port) values ('Port of Victoria, Seychelles', 'Port of Gdansk, Poland');
insert into trips (dep_port, arr_port) values ('Port of Brisbane, Australia', 'Port of Abidjan, Ivory Coast');
insert into trips (dep_port, arr_port) values ('Port of Melbourne, Australia', 'Port of Dakar, Senegal');
insert into trips (dep_port, arr_port) values ('Port of Karachi, Pakistan', 'Port of Riga, Latvia');
insert into trips (dep_port, arr_port) values ('Port of Ningbo-Zhoushan, China', 'Port of Oslo, Norway');
insert into trips (dep_port, arr_port) values ('Port of Auckland, New Zealand', 'Port of Douala, Cameroon');
insert into trips (dep_port, arr_port) values ('Port of Honiara, Solomon Islands', 'Port of Conakry, Guinea');
insert into trips (dep_port, arr_port) values ('Port of Long Beach, USA', 'Port of Montreal, Canada');
insert into trips (dep_port, arr_port) values ('Port of Alexandria, Egypt', 'Port of Dublin, Ireland');
insert into trips (dep_port, arr_port) values ('Port of Hai Phong, Vietnam', 'Port of Thessaloniki, Greece');
insert into trips (dep_port, arr_port) values ('Port of Alexandria, Egypt', 'Port of Dublin, Ireland');
insert into trips (dep_port, arr_port) values ('Port of Noumea, New Caledonia', 'Port of Nouakchott, Mauritania');
insert into trips (dep_port, arr_port) values ('Port of Honiara, Solomon Islands', 'Port of Conakry, Guinea');
insert into trips (dep_port, arr_port) values ('Port of Noumea, New Caledonia', 'Port of Nouakchott, Mauritania');
insert into trips (dep_port, arr_port) values ('Port of Papeete, French Polynesia', 'Port of Banjul, Gambia');
insert into trips (dep_port, arr_port) values ('Port of Hong Kong, Hong Kong', 'Port of Gothenburg, Sweden');
insert into trips (dep_port, arr_port) values ('Port of Manila, Philippines', 'Port of Guayaquil, Ecuador');
insert into trips (dep_port, arr_port) values ('Port of Colombo, Sri Lanka', 'Port of Jeddah, Saudi Arabia');
insert into trips (dep_port, arr_port) values ('Port of Papeete, French Polynesia', 'Port of Banjul, Gambia');
insert into trips (dep_port, arr_port) values ('Port of Antwerp, Belgium', 'Port of Felixstowe, UK');
insert into trips (dep_port, arr_port) values ('Port of Ningbo-Zhoushan, China', 'Port of Oslo, Norway');
insert into trips (dep_port, arr_port) values ('Port of Yangon, Myanmar', 'Port of Constanta, Romania');
insert into trips (dep_port, arr_port) values ('Port of Papeete, French Polynesia', 'Port of Banjul, Gambia');
insert into trips (dep_port, arr_port) values ('Port of Los Angeles, USA', 'Port of Vancouver, Canada');
insert into trips (dep_port, arr_port) values ('Port of Hong Kong, Hong Kong', 'Port of Gothenburg, Sweden');
insert into trips (dep_port, arr_port) values ('Port of Fremantle, Australia', 'Port of Cotonou, Benin');
insert into trips (dep_port, arr_port) values ('Port of Kaohsiung, Taiwan', 'Port of Istanbul, Turkey');
insert into trips (dep_port, arr_port) values ('Port of Barcelona, Spain', 'Port of Colombo, Sri Lanka');
insert into trips (dep_port, arr_port) values ('Port of Manila, Philippines', 'Port of Guayaquil, Ecuador');
insert into trips (dep_port, arr_port) values ('Port of Papeete, French Polynesia', 'Port of Banjul, Gambia');
insert into trips (dep_port, arr_port) values ('Port of Los Angeles, USA', 'Port of Vancouver, Canada');
insert into trips (dep_port, arr_port) values ('Port of Karachi, Pakistan', 'Port of Riga, Latvia');
insert into trips (dep_port, arr_port) values ('Port of Auckland, New Zealand', 'Port of Douala, Cameroon');
insert into trips (dep_port, arr_port) values ('Port of Bangkok, Thailand', 'Port of Algiers, Algeria');
insert into trips (dep_port, arr_port) values ('Port of Hai Phong, Vietnam', 'Port of Thessaloniki, Greece');
insert into trips (dep_port, arr_port) values ('Port of Tanjung Pelepas, Malaysia', 'Port of Haifa, Israel');
insert into trips (dep_port, arr_port) values ('Port of Honiara, Solomon Islands', 'Port of Conakry, Guinea');
insert into trips (dep_port, arr_port) values ('Port of Honiara, Solomon Islands', 'Port of Conakry, Guinea');
insert into trips (dep_port, arr_port) values ('Port of Tauranga, New Zealand', 'Port of Libreville, Gabon');
insert into trips (dep_port, arr_port) values ('Port of Laem Chabang, Thailand', 'Port of Tripoli, Libya');
insert into trips (dep_port, arr_port) values ('Port of Durban, South Africa', 'Port of Lagos, Nigeria');
insert into trips (dep_port, arr_port) values ('Port of Suez, Egypt', 'Port of Reykjavik, Iceland');
insert into trips (dep_port, arr_port) values ('Port of Karachi, Pakistan', 'Port of Riga, Latvia');
insert into trips (dep_port, arr_port) values ('Port of Auckland, New Zealand', 'Port of Douala, Cameroon');
insert into trips (dep_port, arr_port) values ('Port of Busan, South Korea', 'Port of Aarhus, Denmark');
insert into trips (dep_port, arr_port) values ('Port of Guangzhou, China', 'Port of Helsinki, Finland');
insert into trips (dep_port, arr_port) values ('Port of Colombo, Sri Lanka', 'Port of Jeddah, Saudi Arabia');
insert into trips (dep_port, arr_port) values ('Port of Chittagong, Bangladesh', 'Port of Varna, Bulgaria');
insert into trips (dep_port, arr_port) values ('Port of Laem Chabang, Thailand', 'Port of Tripoli, Libya');
insert into trips (dep_port, arr_port) values ('Port of Alexandria, Egypt', 'Port of Dublin, Ireland');
insert into trips (dep_port, arr_port) values ('Port of Guangzhou, China', 'Port of Helsinki, Finland');
insert into trips (dep_port, arr_port) values ('Port of Suva, Fiji', 'Port of Lome, Togo');
insert into trips (dep_port, arr_port) values ('Port of Suez, Egypt', 'Port of Reykjavik, Iceland');
insert into trips (dep_port, arr_port) values ('Port of Busan, South Korea', 'Port of Aarhus, Denmark');
insert into trips (dep_port, arr_port) values ('Port of Brisbane, Australia', 'Port of Abidjan, Ivory Coast');
insert into trips (dep_port, arr_port) values ('Port of Ningbo-Zhoushan, China', 'Port of Oslo, Norway');
insert into trips (dep_port, arr_port) values ('Port of Ho Chi Minh City, Vietnam', 'Port of Tangier, Morocco');
insert into trips (dep_port, arr_port) values ('Port of Port Sudan, Sudan', 'Port of Lisbon, Portugal');
insert into trips (dep_port, arr_port) values ('Port of Kaohsiung, Taiwan', 'Port of Istanbul, Turkey');
insert into trips (dep_port, arr_port) values ('Port of Hai Phong, Vietnam', 'Port of Thessaloniki, Greece');
insert into trips (dep_port, arr_port) values ('Port of Laem Chabang, Thailand', 'Port of Tripoli, Libya');
insert into trips (dep_port, arr_port) values ('Port of Busan, South Korea', 'Port of Aarhus, Denmark');
insert into trips (dep_port, arr_port) values ('Port of Alexandria, Egypt', 'Port of Dublin, Ireland');
insert into trips (dep_port, arr_port) values ('Port of Colombo, Sri Lanka', 'Port of Jeddah, Saudi Arabia');
insert into trips (dep_port, arr_port) values ('Port of Barcelona, Spain', 'Port of Colombo, Sri Lanka');
insert into trips (dep_port, arr_port) values ('Port of Noumea, New Caledonia', 'Port of Nouakchott, Mauritania');
insert into trips (dep_port, arr_port) values ('Port of Long Beach, USA', 'Port of Montreal, Canada');
insert into trips (dep_port, arr_port) values ('Port of Busan, South Korea', 'Port of Aarhus, Denmark');
insert into trips (dep_port, arr_port) values ('Port of Long Beach, USA', 'Port of Montreal, Canada');
insert into trips (dep_port, arr_port) values ('Port of Singapore, Singapore', 'Port of Piraeus, Greece');
insert into trips (dep_port, arr_port) values ('Port of Le Havre, France', 'Port of San Antonio, Chile');
insert into trips (dep_port, arr_port) values ('Port of Guangzhou, China', 'Port of Helsinki, Finland');
insert into trips (dep_port, arr_port) values ('Port of Le Havre, France', 'Port of San Antonio, Chile');
insert into trips (dep_port, arr_port) values ('Port of Honiara, Solomon Islands', 'Port of Conakry, Guinea');
insert into trips (dep_port, arr_port) values ('Port of Shanghai, China', 'Port of Valencia, Spain');
insert into trips (dep_port, arr_port) values ('Port of Chittagong, Bangladesh', 'Port of Varna, Bulgaria');
insert into trips (dep_port, arr_port) values ('Port of Yokohama, Japan', 'Port of Djibouti, Djibouti');
insert into trips (dep_port, arr_port) values ('Port of Fremantle, Australia', 'Port of Cotonou, Benin');
insert into trips (dep_port, arr_port) values ('Port of Tauranga, New Zealand', 'Port of Libreville, Gabon');
insert into trips (dep_port, arr_port) values ('Port of Melbourne, Australia', 'Port of Dakar, Senegal');
insert into trips (dep_port, arr_port) values ('Port of Brisbane, Australia', 'Port of Abidjan, Ivory Coast');
insert into trips (dep_port, arr_port) values ('Port of Victoria, Seychelles', 'Port of Gdansk, Poland');
insert into trips (dep_port, arr_port) values ('Port of Guangzhou, China', 'Port of Helsinki, Finland');
insert into trips (dep_port, arr_port) values ('Port of Ningbo-Zhoushan, China', 'Port of Oslo, Norway');
insert into trips (dep_port, arr_port) values ('Port of Santos, Brazil', 'Port of Luanda, Angola');
